[package]
name = "link-ffi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "link_ffi"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
required-features = ["uniffi/cli"]

[dependencies]
link-endpoint = { path = "../link-endpoint" }
link-engine = { path = "../link-engine" }
link-websocket = { path = "../link-websocket" }
thiserror.workspace = true
tokio.workspace = true
uniffi.workspace = true

[dev-dependencies]
link-core = { path = "../link-core" }
link-relay = { path = "../link-relay" }
hex.workspace = true
rustls.workspace = true
zeroize.workspace = true
